version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASS
      POSTGRES_DB: DB_NAME
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: express_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=DB_HOST
      - DB_USER=DB_USER
      - DB_PASS=DB_PASS
      - DB_NAME=DB_NAME
    depends_on:
      - db

volumes:
  dbdata:
